### ISSUE TITLE
Order Edit in Backend not possible

### ISSUE THREAD

**Issue by mautz-et-tong** [PAYONE-GmbH/magento-2#158]
Magento 2.2.2
Payone_Core v2.1.0

When trying to edit an order in the backend, the following error appears:
Invalid template file: 'form/base.phtml' in module: 'Payone_Core' block's name: 'payone_obt_ideal'

The form/base.phml is in the frontend template folder.

(Stupid Quick Fix: cp base.phtml to view/adminhtml/templates/form/base.phtml)

**Comment by fjbender** [comment]
Where exactly does the error message appear? I can't really find it anywhere. However, it makes sense that something is wrong because the template is not in the adminhtml folder.

**Comment by mautz-et-tong** [comment]
The error appears, if you click edit on an order in the backend order list.
Error:
`1 exception(s):
Exception #0 (Magento\Framework\Exception\ValidatorException): Invalid template file: 'form/base.phtml' in module: 'Payone_Core' block's name: 'payone_obt_ideal'

Exception #0 (Magento\Framework\Exception\ValidatorException): Invalid template file: 'form/base.phtml' in module: 'Payone_Core' block's name: 'payone_obt_ideal'
#0 __release_path__/vendor/magento/framework/View/Element/Template.php(300): Magento\Framework\View\Element\Template->fetchView(false)
#1 __release_path__/vendor/magento/framework/View/Element/AbstractBlock.php(667): Magento\Framework\View\Element\Template->_toHtml()
#2 __release_path__/vendor/magento/framework/View/Layout.php(558): Magento\Framework\View\Element\AbstractBlock->toHtml()
#3 __release_path__/vendor/magento/framework/View/Layout.php(534): Magento\Framework\View\Layout->_renderBlock('payone_obt_idea...')
#4 __release_path__/vendor/magento/framework/View/Layout.php(489): Magento\Framework\View\Layout->renderNonCachedElement('payone_obt_idea...')
#5 __release_path__/vendor/magento/framework/View/Element/AbstractBlock.php(507): Magento\Framework\View\Layout->renderElement('payone_obt_idea...', true)
#6 __release_path__/vendor/magento/module-sales/view/adminhtml/templates/order/create/billing/method/form.phtml(47): Magento\Framework\View\Element\AbstractBlock->getChildHtml('payment.method....')
#7 __release_path__/vendor/magento/framework/View/TemplateEngine/Php.php(59): include('/var/www/releas...')
#8 __release_path__/vendor/magento/framework/View/Element/Template.php(270): Magento\Framework\View\TemplateEngine\Php->render(Object(Magento\Sales\Block\Adminhtml\Order\Create\Billing\Method\Form), '/var/www/releas...', Array)
#9 __release_path__/vendor/magento/framework/View/Element/Template.php(300): Magento\Framework\View\Element\Template->fetchView('/var/www/releas...')
#10 __release_path__/vendor/magento/framework/View/Element/AbstractBlock.php(667): Magento\Framework\View\Element\Template->_toHtml()
#11 __release_path__/vendor/magento/framework/View/Layout.php(558): Magento\Framework\View\Element\AbstractBlock->toHtml()
#12 __release_path__/vendor/magento/framework/View/Layout.php(534): Magento\Framework\View\Layout->_renderBlock('order_create_bi...')
#13 __release_path__/vendor/magento/framework/View/Layout.php(489): Magento\Framework\View\Layout->renderNonCachedElement('order_create_bi...')
#14 __release_path__/vendor/magento/framework/View/Element/AbstractBlock.php(511): Magento\Framework\View\Layout->renderElement('order_create_bi...', true)
#15 __release_path__/vendor/magento/module-sales/view/adminhtml/templates/order/create/abstract.phtml(18): Magento\Framework\View\Element\AbstractBlock->getChildHtml('', true)
#16 __release_path__/vendor/magento/framework/View/TemplateEngine/Php.php(59): include('/var/www/releas...')
#17 __release_path__/vendor/magento/framework/View/Element/Template.php(270): Magento\Framework\View\TemplateEngine\Php->render(Object(Magento\Sales\Block\Adminhtml\Order\Create\Billing\Method), '/var/www/releas...', Array)
#18 __release_path__/vendor/magento/framework/View/Element/Template.php(300): Magento\Framework\View\Element\Template->fetchView('/var/www/releas...')
#19 __release_path__/vendor/magento/module-backend/Block/Template.php(124): Magento\Framework\View\Element\Template->_toHtml()
#20 __release_path__/vendor/magento/framework/View/Element/AbstractBlock.php(667): Magento\Backend\Block\Template->_toHtml()
#21 __release_path__/vendor/magento/framework/View/Layout.php(558): Magento\Framework\View\Element\AbstractBlock->toHtml()
#22 __release_path__/vendor/magento/framework/View/Layout.php(534): Magento\Framework\View\Layout->_renderBlock('billing_method')
#23 __release_path__/vendor/magento/framework/View/Layout.php(489): Magento\Framework\View\Layout->renderNonCachedElement('billing_method')
#24 __release_path__/vendor/magento/framework/View/Element/AbstractBlock.php(507): Magento\Framework\View\Layout->renderElement('billing_method', true)
#25 __release_path__/vendor/magento/module-sales/view/adminhtml/templates/order/create/data.phtml(56): Magento\Framework\View\Element\AbstractBlock->getChildHtml('billing_method')
#26 __release_path__/vendor/magento/framework/View/TemplateEngine/Php.php(59): include('/var/www/releas...')
#27 __release_path__/vendor/magento/framework/View/Element/Template.php(270): Magento\Framework\View\TemplateEngine\Php->render(Object(Magento\Sales\Block\Adminhtml\Order\Create\Data), '/var/www/releas...', Array)
#28 __release_path__/vendor/magento/framework/View/Element/Template.php(300): Magento\Framework\View\Element\Template->fetchView('/var/www/releas...')
#29 __release_path__/vendor/magento/module-backend/Block/Template.php(124): Magento\Framework\View\Element\Template->_toHtml()
#30 __release_path__/vendor/magento/framework/View/Element/AbstractBlock.php(667): Magento\Backend\Block\Template->_toHtml()
#31 __release_path__/vendor/magento/framework/View/Layout.php(558): Magento\Framework\View\Element\AbstractBlock->toHtml()
#32 __release_path__/vendor/magento/framework/View/Layout.php(534): Magento\Framework\View\Layout->_renderBlock('data')
#33 __release_path__/vendor/magento/framework/View/Layout.php(489): Magento\Framework\View\Layout->renderNonCachedElement('data')
#34 __release_path__/vendor/magento/framework/View/Element/AbstractBlock.php(507): Magento\Framework\View\Layout->renderElement('data', true)
#35 __release_path__/vendor/magento/module-sales/view/adminhtml/templates/order/create/form.phtml(23): Magento\Framework\View\Element\AbstractBlock->getChildHtml('data')
#36 __release_path__/vendor/magento/framework/View/TemplateEngine/Php.php(59): include('/var/www/releas...')
#37 __release_path__/vendor/magento/framework/View/Element/Template.php(270): Magento\Framework\View\TemplateEngine\Php->render(Object(Magento\Sales\Block\Adminhtml\Order\Create\Form), '/var/www/releas...', Array)
#38 __release_path__/vendor/magento/framework/View/Element/Template.php(300): Magento\Framework\View\Element\Template->fetchView('/var/www/releas...')
#39 __release_path__/vendor/magento/module-backend/Block/Template.php(124): Magento\Framework\View\Element\Template->_toHtml()
#40 __release_path__/vendor/magento/framework/View/Element/AbstractBlock.php(667): Magento\Backend\Block\Template->_toHtml()
#41 __release_path__/vendor/magento/framework/View/Layout.php(558): Magento\Framework\View\Element\AbstractBlock->toHtml()
#42 __release_path__/vendor/magento/framework/View/Layout.php(534): Magento\Framework\View\Layout->_renderBlock('order_create_fo...')
#43 __release_path__/vendor/magento/framework/View/Layout.php(489): Magento\Framework\View\Layout->renderNonCachedElement('order_create_fo...')
#44 __release_path__/vendor/magento/framework/View/Element/AbstractBlock.php(507): Magento\Framework\View\Layout->renderElement('order_create_fo...', true)
#45 __release_path__/vendor/magento/module-backend/Block/Widget/Form/Container.php(191): Magento\Framework\View\Element\AbstractBlock->getChildHtml('form')
#46 __release_path__/vendor/magento/module-backend/view/adminhtml/templates/widget/form/container.phtml(15): Magento\Backend\Block\Widget\Form\Container->getFormHtml()
#47 __release_path__/vendor/magento/framework/View/TemplateEngine/Php.php(59): include('/var/www/releas...')
#48 __release_path__/vendor/magento/framework/View/Element/Template.php(270): Magento\Framework\View\TemplateEngine\Php->render(Object(Magento\Sales\Block\Adminhtml\Order\Create), '/var/www/releas...', Array)
#49 __release_path__/vendor/magento/framework/View/Element/Template.php(300): Magento\Framework\View\Element\Template->fetchView('/var/www/releas...')
#50 __release_path__/vendor/magento/module-backend/Block/Template.php(124): Magento\Framework\View\Element\Template->_toHtml()
#51 __release_path__/vendor/magento/framework/View/Element/AbstractBlock.php(667): Magento\Backend\Block\Template->_toHtml()
#52 __release_path__/vendor/magento/framework/View/Layout.php(558): Magento\Framework\View\Element\AbstractBlock->toHtml()
#53 __release_path__/vendor/magento/framework/View/Layout.php(534): Magento\Framework\View\Layout->_renderBlock('order_content')
#54 __release_path__/vendor/magento/framework/View/Layout.php(489): Magento\Framework\View\Layout->renderNonCachedElement('order_content')
#55 __release_path__/vendor/magento/framework/View/Layout.php(585): Magento\Framework\View\Layout->renderElement('order_content')
#56 __release_path__/vendor/magento/framework/View/Layout.php(536): Magento\Framework\View\Layout->_renderContainer('content')
#57 __release_path__/vendor/magento/framework/View/Layout.php(489): Magento\Framework\View\Layout->renderNonCachedElement('content')
#58 __release_path__/vendor/magento/framework/View/Layout.php(585): Magento\Framework\View\Layout->renderElement('content')
#59 __release_path__/vendor/magento/framework/View/Layout.php(536): Magento\Framework\View\Layout->_renderContainer('main.col')
#60 __release_path__/vendor/magento/framework/View/Layout.php(489): Magento\Framework\View\Layout->renderNonCachedElement('main.col')
#61 __release_path__/vendor/magento/framework/View/Layout.php(585): Magento\Framework\View\Layout->renderElement('main.col')
#62 __release_path__/vendor/magento/framework/View/Layout.php(536): Magento\Framework\View\Layout->_renderContainer('admin.scope.col...')
#63 __release_path__/vendor/magento/framework/View/Layout.php(489): Magento\Framework\View\Layout->renderNonCachedElement('admin.scope.col...')
#64 __release_path__/vendor/magento/framework/View/Layout.php(585): Magento\Framework\View\Layout->renderElement('admin.scope.col...')
#65 __release_path__/vendor/magento/framework/View/Layout.php(536): Magento\Framework\View\Layout->_renderContainer('page.main.conta...')
#66 __release_path__/vendor/magento/framework/View/Layout.php(489): Magento\Framework\View\Layout->renderNonCachedElement('page.main.conta...')
#67 __release_path__/vendor/magento/framework/View/Layout.php(585): Magento\Framework\View\Layout->renderElement('page.main.conta...')
#68 __release_path__/vendor/magento/framework/View/Layout.php(536): Magento\Framework\View\Layout->_renderContainer('page.content')
#69 __release_path__/vendor/magento/framework/View/Layout.php(489): Magento\Framework\View\Layout->renderNonCachedElement('page.content')
#70 __release_path__/vendor/magento/framework/View/Layout.php(585): Magento\Framework\View\Layout->renderElement('page.content')
#71 __release_path__/vendor/magento/framework/View/Layout.php(536): Magento\Framework\View\Layout->_renderContainer('page.wrapper')
#72 __release_path__/vendor/magento/framework/View/Layout.php(489): Magento\Framework\View\Layout->renderNonCachedElement('page.wrapper')
#73 __release_path__/vendor/magento/framework/View/Layout.php(585): Magento\Framework\View\Layout->renderElement('page.wrapper')
#74 __release_path__/vendor/magento/framework/View/Layout.php(536): Magento\Framework\View\Layout->_renderContainer('backend.page')
#75 __release_path__/vendor/magento/framework/View/Layout.php(489): Magento\Framework\View\Layout->renderNonCachedElement('backend.page')
#76 __release_path__/vendor/magento/framework/View/Layout.php(585): Magento\Framework\View\Layout->renderElement('backend.page')
#77 __release_path__/vendor/magento/framework/View/Layout.php(536): Magento\Framework\View\Layout->_renderContainer('root')
#78 __release_path__/vendor/magento/framework/View/Layout.php(489): Magento\Framework\View\Layout->renderNonCachedElement('root')
#79 __release_path__/vendor/magento/framework/View/Layout.php(954): Magento\Framework\View\Layout->renderElement('root')
#80 __release_path__/generated/code/Magento/Framework/View/Layout/Interceptor.php(37): Magento\Framework\View\Layout->getOutput()
#81 __release_path__/vendor/magento/framework/View/Result/Page.php(257): Magento\Framework\View\Layout\Interceptor->getOutput()
#82 __release_path__/vendor/magento/framework/View/Result/Layout.php(170): Magento\Framework\View\Result\Page->render(Object(Magento\Framework\App\Response\Http\Interceptor))
#83 __release_path__/generated/code/Magento/Backend/Model/View/Result/Page/Interceptor.php(24): Magento\Framework\View\Result\Layout->renderResult(Object(Magento\Framework\App\Response\Http\Interceptor))
#84 __release_path__/vendor/magento/framework/App/Http.php(139): Magento\Backend\Model\View\Result\Page\Interceptor->renderResult(Object(Magento\Framework\App\Response\Http\Interceptor))
#85 __release_path__/vendor/magento/framework/App/Bootstrap.php(256): Magento\Framework\App\Http->launch()
#86 __release_path__/pub/index.php(37): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http\Interceptor))
#87 {main}`

I have seen the new release 2.2 from yesterday, will test it and report back.

**Comment by mautz-et-tong** [comment]
I can confirm: still not fixed in v2.2.0.
In Backend, go to sales->orders.
Select an order by clicking View in the grid.
In the view with the selected order press edit, click ok in the PopUp

**Comment by steros** [comment]
Maybe this is related? #160

**Comment by fjbender** [comment]
Yes, I think #160 is the same issue, I closed it in favor of this issue.

I was able to reproduce it and we'll get it fixed.

**Comment by AykutCevik** [comment]
@fjbender in which release will this be included and when can we expect this release? Thank you for the fix.

**Comment by fjbender** [comment]
@AykutCevik We're aiming to have a release next week.
